// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzkpsidpbwxswrbqoock.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6a3BzaWRwYnd4c3dyYnFvb2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDQzMzAsImV4cCI6MjA3MjQ4MDMzMH0.nKpvRL6oPZE9WIGBan2SiSX8Y8w6mCjPYQoWcuRddE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});